### ISSUE TITLE
Playback of TTS on grouped speakers

### ISSUE THREAD

**Issue by chheiss** [jjlawren/sonos_cloud#29]
Hi! Is there a way to play back TTS on grouped speakers?
Thanks!

**Comment by jjlawren** [comment]
This API ignores any group structure (as it's an overlay alert sound), so you'd need to list each speaker in the call:
```yaml
service: media_player.play_media
data:
  entity_id:
    - media_player.kitchen
    - media_player.bedroom
  media_content_id: media-source://tts/cloud?message=I am very loud
  media_content_type: music
  extra:
    play_on_bonded: true
```
The `play_on_bonded` makes it play on every speaker in bonded rooms, like a home theater or stereo pair.

This tries to synchronize playback by making the API calls simultaneously, but it's not guaranteed and may occasionally be slightly out of sync.
