### ISSUE TITLE
Provider cloud not found (unknown_error)

### ISSUE THREAD

**Issue by PedroKTFC** [jjlawren/sonos_cloud#40]
I am trying the text to speach example given in the instructions:
```
service: media_player.play_media
data:
  entity_id: media_player.kitchen
  media_content_id: media-source://tts/cloud?message=I am very loud
  media_content_type: music
  extra:
    volume: 80
```
However, when I try it in Developer Tools>Services I get a "Provider cloud not found error" and the following in the log:

> Logger: homeassistant.components.websocket_api.http.connection
> Source: components/websocket_api/connection.py:150
> Integration: Home Assistant WebSocket API (documentation, issues)
> First occurred: 10:23:21 (4 occurrences)
> Last logged: 13:57:26
> 
> [2584235168] Error handling message: Provider cloud not found (unknown_error) from xx.xx.xx.xx (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0)
> [2582515920] Error handling message: Provider cloud not found (unknown_error) from xx.xx.xx.xx (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0)
> [2545034600] Error handling message: Provider cloud not found (unknown_error) from xx.xx.xx.xx (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0)

I imagine I'm making a basic mistake but I've no idea what? Can anyone help?
