### ISSUE TITLE
Playing an MP3 over Sonos

### ISSUE THREAD

**Issue by pwcutajar** [jjlawren/sonos_cloud#48]
Hi

I have the following working#

![image](https://github.com/jjlawren/sonos_cloud/assets/75051501/5a6bd698-213c-4373-8594-b3dd5d0242eb)

but i can get the following to work any help I would be grateful

![image](https://github.com/jjlawren/sonos_cloud/assets/75051501/373027b4-7a2e-46d9-9838-2038b45c1a75)

**Comment by pwcutajar** [comment]
Anybody?

**Comment by jjlawren** [comment]
When playing local media, it's easier to get the URL correct by using the script/automation UI and selecting the your media that way. You can then copy the media_content_id & type to other automations.

**Comment by pwcutajar** [comment]
jjlawren thanks for coming back to me

Im a bit confused by your answer, ive followed the example in the documentation but to no avail. Can you get it to work at your end and paste a screen shot of the setup?

![image](https://github.com/jjlawren/sonos_cloud/assets/75051501/2964bcdf-7ea5-4f48-977b-323c2f6b803a)

ive also tried 

media_content_id: media-source://local/doorbell-1/mp3

neither play. ( its a shame but im working remotely HA reports success but i cant get to any sonos log files)

**Comment by jjlawren** [comment]
1. Create a new automation or script (you won't need to save it).
2. Choose the "Play media" action.
3. Select your Sonos device and choose your file using the UI media browser.
4. Switch to YAML for the service call it generates, which you can copy & paste into other automations. The important data will look like this:
```yaml
service: media_player.play_media
target:
  entity_id: media_player.sonos_basement
data:
  media_content_id: media-source://media_source/sound_files/doorbell-front.mp3
  media_content_type: audio/mpeg
```
![image](https://github.com/jjlawren/sonos_cloud/assets/1203111/5c1570e5-b985-4e62-ae17-a47765705743)
