### ISSUE TITLE
Announcements / TTS does not work anymore

### ISSUE THREAD

**Issue by xteaun** [jjlawren/sonos_cloud#50]
I had my Sonos speakers set up to play messages to me when I ask the voice assistant questions. After one of the last HA updates the TTS stopped working. When I call the service, as described in the documentation, I get a green tick, but no audio plays:

```
service: media_player.play_media
data:
  entity_id: media_player.kitchen
  media_content_id: media-source://tts/cloud?message=I am very loud
  media_content_type: music
  extra:
    volume: 80
```
What am I doing wrong? :) Is this a bug?
