### ISSUE TITLE
Volume level not corresponding with official Sonos integration

### ISSUE THREAD

**Issue by TyzzyT** [jjlawren/sonos_cloud#9]
When I want to play some audio item with the official Sonos integration, I can set the volume with a slider from 0.0 till 1.0
With this integration, the volume is set from 1 till 100. I think it makes more sense to have these volume levels be the same. Can this please be adjusted so that these values are matching?

For now I solved this myself by templating the volume level in the script:
```
service: media_player.play_media
data:
  entity_id: media_player.sonos_cloud_werkkamer
  media_content_id: https://_redacted_/local/audio_notifications/{{ message }}.mp3
  media_content_type: music
  extra:
    volume: '{{ volume_level | float * 100 }}'
```

**Comment by jjlawren** [comment]
The volumes on the `media_player` entities in this integration are currently unused.

**Comment by TyzzyT** [comment]
What do you mean with unused? I'm not talking about reading the value, I'm talking about setting the value when playing audio on the Sonos device.
You documentation says that setting the volume is supported:
[https://github.com/jjlawren/sonos_cloud#examples](https://github.com/jjlawren/sonos_cloud#examples)
```
service: media_player.play_media
data:
  entity_id: media_player.kitchen
  media_content_id: https://<unique_cloud_id>.ui.nabu.casa/local/sound_files/doorbell.mp3
  media_content_type: music
  extra:
    volume: 35
```
And this works too. When I set the volume to 80 it is way louder then when I give it value 30.

But my problem is: when I use the play audio service towards the original Sonos entity, I have to use a value of 0.3 to have it play at the same loudness as when I use value 30 with your integration.
